const CONFIG=window.EEVEE_BOX_CONFIG||{};const KEY='EEVEE_BOX_DATA_V1';let data=[];let editing=null;
const $=s=>document.querySelector(s);const grid=$('#grid'),toast=$('#toast');
function say(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
async function api(action,payload={}){if(!CONFIG.apiEndpoint)throw new Error('API endpoint missing');const r=await fetch(CONFIG.apiEndpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const x=await r.json();if(!x.ok)throw new Error(x.error||'API error');return x;}
async function load(){const seed=await fetch('pokemon-data.json').then(r=>r.json());const local=JSON.parse(localStorage.getItem(KEY)||'null');data=local||seed; if(CONFIG.apiEndpoint){try{const x=await api('get_all');if(x.records?.length)data=x.records;else await api('seed',{records:data});setSync(true)}catch(e){console.warn(e);setSync(false)}} render();}
function setSync(ok){$('#syncDot').classList.toggle('online',ok);$('#syncText').textContent=ok?'온라인 동기화':'로컬 모드'}
function persist(){localStorage.setItem(KEY,JSON.stringify(data));}
async function saveRecord(p){p.updatedAt=new Date().toISOString();persist();render();if(CONFIG.apiEndpoint){try{await api('save',{record:p});setSync(true)}catch(e){setSync(false);say('로컬에는 저장됐어요')}}}
function types(){return [...new Set(data.flatMap(p=>p.types||[]))].sort()}
function render(){const q=$('#searchInput').value.trim().toLowerCase(),t=$('#typeFilter').value;const filtered=data.filter(p=>!q||[p.nickname,p.species,p.ability,...(p.types||[])].join(' ').toLowerCase().includes(q)).filter(p=>!t||(p.types||[]).includes(t));$('#countText').textContent=`${filtered.length}마리`;grid.innerHTML=filtered.sort((a,b)=>(a.order||99)-(b.order||99)).map(card).join('');grid.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));grid.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>changeLevel(b.dataset.level,Number(b.dataset.delta)));}
function card(p){return `<article class="card"><div class="card-head"><div><h3>${esc(p.nickname||p.species)}</h3><div class="species">${esc(p.species)}</div></div><button data-edit="${p.id}">수정</button></div><div class="badges">${(p.types||[]).map(x=>`<span class="badge">${esc(x)}</span>`).join('')}${p.teraType?`<span class="badge">테라 ${esc(p.teraType)}</span>`:''}</div><div class="level-row"><span>현재 레벨</span><strong>Lv.${p.level||1}</strong><div class="level-controls"><button data-level="${p.id}" data-delta="-1">−</button><button data-level="${p.id}" data-delta="1">+</button></div></div><ul class="moves">${[0,1,2,3].map(i=>`<li>${esc((p.currentMoves||[])[i]||'—')}</li>`).join('')}</ul><div class="card-foot"><span>${esc(p.ability||'특성 미입력')}</span><span>${p.heldItem?esc(p.heldItem):'도구 없음'}</span></div></article>`}
function changeLevel(id,d){const p=data.find(x=>x.id===id);if(!p)return;p.level=Math.max(1,Math.min(100,(Number(p.level)||1)+d));saveRecord(p);}
function openEditor(id){editing=id?data.find(x=>x.id===id):{id:'p'+Date.now(),order:data.length+1,nickname:'',species:'',level:1,types:[],ability:'',abilityEffect:'',teraType:'',nature:'',heldItem:'',notes:'',currentMoves:[],moves:[]};$('#editorTitle').textContent=id?'포켓몬 수정':'포켓몬 추가';$('#editId').value=editing.id;$('#editNickname').value=editing.nickname||'';$('#editSpecies').value=editing.species||'';$('#editLevel').value=editing.level||1;$('#editTypes').value=(editing.types||[]).join(', ');$('#editAbility').value=editing.ability||'';$('#editAbilityEffect').value=editing.abilityEffect||'';$('#editTera').value=editing.teraType||'';$('#editNature').value=editing.nature||'';$('#editItem').value=editing.heldItem||'';$('#editNotes').value=editing.notes||'';renderMoveInputs();renderMoveLibrary();$('#deleteButton').style.visibility=id?'visible':'hidden';$('#editor').showModal();}
function renderMoveInputs(){const opts=['',...(editing.moves||[]).map(m=>m.name),...(editing.currentMoves||[])];const unique=[...new Set(opts)];$('#moveSelects').innerHTML=[0,1,2,3].map(i=>`<select class="move-select"><option value="">— 비움 —</option>${unique.filter(Boolean).map(x=>`<option ${x===(editing.currentMoves||[])[i]?'selected':''}>${esc(x)}</option>`).join('')}</select>`).join('')}
function renderMoveLibrary(){const q=$('#moveSearch').value.trim().toLowerCase();$('#moveLibrary').innerHTML=(editing.moves||[]).filter(m=>!q||m.name.toLowerCase().includes(q)).map(m=>`<div class="move-row"><strong>${esc(m.name)} · ${esc(m.type)} · ${esc(m.category)}</strong><span>${esc(m.method)}${m.learnLevel&&m.learnLevel!=='-'?' Lv.'+esc(m.learnLevel):''} / 위력 ${esc(m.power||'-')} / 명중 ${esc(m.accuracy||'-')}</span></div>`).join('')||'<div class="move-row">등록된 기술 데이터가 없어요.</div>'}
$('#editorForm').onsubmit=e=>{e.preventDefault();Object.assign(editing,{nickname:$('#editNickname').value.trim(),species:$('#editSpecies').value.trim(),level:Number($('#editLevel').value),types:$('#editTypes').value.split(',').map(x=>x.trim()).filter(Boolean),ability:$('#editAbility').value.trim(),abilityEffect:$('#editAbilityEffect').value.trim(),teraType:$('#editTera').value.trim(),nature:$('#editNature').value.trim(),heldItem:$('#editItem').value.trim(),notes:$('#editNotes').value.trim(),currentMoves:[...document.querySelectorAll('.move-select')].map(x=>x.value).filter(Boolean)});if(!data.some(x=>x.id===editing.id))data.push(editing);saveRecord(editing);$('#editor').close();say('저장했어요')};
$('#deleteButton').onclick=async()=>{if(!confirm('이 포켓몬을 삭제할까요?'))return;data=data.filter(x=>x.id!==editing.id);persist();render();$('#editor').close();if(CONFIG.apiEndpoint)try{await api('remove',{id:editing.id})}catch{}say('삭제했어요')};
$('#closeEditor').onclick=()=>$('#editor').close();$('#addButton').onclick=()=>openEditor();$('#searchInput').oninput=render;$('#typeFilter').onchange=render;$('#moveSearch').oninput=renderMoveLibrary;$('#syncButton').onclick=async()=>{if(!CONFIG.apiEndpoint)return say('config.js에 Apps Script 주소를 넣어주세요');try{const x=await api('get_all');if(x.records?.length){data=x.records;persist();render()}setSync(true);say('동기화했어요')}catch(e){setSync(false);say('동기화에 실패했어요')}};
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
(async()=>{const sel=$('#typeFilter');await load();types().forEach(t=>sel.insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));})();